# fly.toml
app = "manhattan-dashboard-gc"  # Change to your preferred app name

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  PORT = "8050"

[http_service]
  internal_port = 8050
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0